### ISSUE TITLE
"gamemd-spawn.exe - Application Error" 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#21]
"The application was unable to start correctly (0xc0000142). Click OK to close the application"

**Comment by Rampastring** [comment]
Resolved by deleting wsock32.dll.

**Comment by GrantBartlett** [comment]
Not yet resolved, push in the next update

**Comment by GrantBartlett** [comment]
Does client check on new opens, or just once? It appears users copy and paste wsock32.dll for Mental Omega.

**Comment by Rampastring** [comment]
As it is, the client deletes the wsock32.dll file each time an update is downloaded.

**Comment by Rampastring** [comment]
With the next update wsock32.dll will always be removed as the client is started.

**Comment by GrantBartlett** [comment]
Still re-appearing, has this update been applied?

**Comment by Rampastring** [comment]
It has been applied now, with version 1.85.
