### ISSUE TITLE
Catch exception if can't edit file due to permissions

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#25]
![Error permissions](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xft1/v/t1.0-9/12042772_10207284554090441_281143349915237190_n.jpg?oh=d57e974c84ce0e640933df58e7503f6d&oe=56646959)
https://www.facebook.com/photo.php?fbid=10207284554090441&set=o.484330335019909&type=3

**Comment by Rampastring** [comment]
The client already has code that should prevent that. You should see a message like this http://rampastring.cncnet.org/needadmin.png when starting the client.

**Comment by Rampastring** [comment]
Unless this is seen more or it's shown that people aren't getting the message in my prior comment when they should (I personally get it always when the client can't write to the files in its directory), I think this is solved.

The only case where you can get the message is if the client is for some reason able to access other files in the directory, but not RA2MD.ini.
