### ISSUE TITLE
Kaboom - DateTime Date.Time.MinValue...

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#27]
Reports of this error on startup, and/or finishing a game.

(https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/12039723_10204970232955148_8017735908212577610_n.jpg?oh=7f81f848d7d4378a9008c3b5f3102465&oe=569B3298)

**Comment by GrantBartlett** [comment]
http://cnc-comm.com/community/index.php?topic=4513.msg33904#msg33904

**Comment by GrantBartlett** [comment]
EDIT: Is this a possible solution: Remove dscore.dat
http://cnc-comm.com/community/index.php?topic=4490.msg33989#msg33989

**Comment by Rampastring** [comment]
Yes, removing dscore.dat is the solution. I don't know why the error happened, but it shouldn't happen anymore as I made the client not create the dscore.dat file when playing YR.

**Comment by GrantBartlett** [comment]
Just noticed when testing, this file is generated again: dscore.dat

Double check?

**Comment by Rampastring** [comment]
Are you sure that you're using the test build and the file wasn't there to begin with? If so, were you playing Skirmish or on CnCNet?

**Comment by GrantBartlett** [comment]
Using the test build, and it Date modified said Today - TIME etc.

**Comment by GrantBartlett** [comment]
Confirmed: http://cnc-comm.com/community/index.php?topic=4492.msg34477#msg34477

**Comment by Rampastring** [comment]
With the public version, of course. I'm asking you to replicate it with the test build.

**Comment by GrantBartlett** [comment]
Doesn't appear to be there now.

**Comment by Rampastring** [comment]
Okay, I just replicated it on CnCNet. Will look into fixing it.

**Comment by Rampastring** [comment]
I uploaded a new test build update. Please test both Skirmish and CnCNet games and check that dscore.dat isn't created.

**Comment by GrantBartlett** [comment]
I can't seem to replicate, will ask Tomson to also test.

**Comment by GrantBartlett** [comment]
Can we push this fix please? Keep getting messages

--

hi the client wont load saying this ...kaboom
Unhandled exception!!!
8. 10. 14:03:40.579 The binary data must result in a DateTime with ticks between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.
Parameter name: dateData
any ideas whats up ???

**Comment by Rampastring** [comment]
Fixed in the latest public update, version 1.85.
