### ISSUE TITLE
TS-DDRAW breaks Origin Launch 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#30]
We need to find a middle ground by enabling ts-ddraw by default, and removing it for playing on Origin.

Any ideas?

--
## Ideas:

FunkyFr3sh: Another idea: do not put ts-ddraw in the folder. On the second game start show a message box and ask if the game worked, if not put ts-ddraw in the folder automatically.

FunkyFr3sh:  ts-ddraw could also check the filename and disable itself if not run via spawner

 --
## Installer Fixes
FunkyFr3sh is applying the following to the installer:
A checkbox to the installer so everyone who tries to use the installer on installation with broken SP can just tick the box and get the fix.

[x] Apply Black Screen/Performance fix

**Comment by Rampastring** [comment]
I have made the latest YR client remove ddraw.dll from the game dir on exit. When you enter the Skirmish or CnCNet lobby, the ddraw.dll is placed back into the directory for the session (if TS-DDRAW is enabled, that is).
