### ISSUE TITLE
Host has kicked you from the game

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#31]
https://www.facebook.com/CnCNet/posts/835091449943794

What other solutions are there? I have already told the guy to remove the INI directory - same result

**Comment by Rampastring** [comment]
I've revised some anticheat code, so maybe the next update will fix it. If not, I'd need to test it with someone trustworthy who encounters the issue.

**Comment by Rampastring** [comment]
Also, it's likely the same issue as this one https://github.com/CnCNet/yr-client/issues/22
