### ISSUE TITLE
Unable to launch, player X is still playing the game

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#32]
![error](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xtp1/v/t35.0-12/12076312_10206299602543315_1608323899_o.jpg?oh=4b610ffb069c213057b8da1bc4d4efd6&oe=560EC8F5)

The player cannot launch the game

His/her comments:
I tried even rebooting, killing all processes, but neither made it work again.

Is there more to that error than just what it says?

**Comment by Rampastring** [comment]
Nope, happens only if gamemd-spawn.exe is still running after a game.
In theory, it could also be the client not detecting that gamemd-spawn.exe has exited, but this has never happened.

**Comment by Rampastring** [comment]
System-specific issue.
