### ISSUE TITLE
Kaboom - Can't access expandmd02.mix 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#36]
Being used by another process. Got a couple of messages about this error now

**Comment by GrantBartlett** [comment]
More reports 

So far, even when RA2 mode is NOT checked for this guy, the client is looking for it and on immediate launch the client crashes.

**Comment by GrantBartlett** [comment]
Confirmed bug:

If someone hosts, enables it, plays. Then disables RA2 Mode and then plays, it crashes. 

Please investigate ASAP! This also breaks YR play because its looking for ra2 mode.

**Comment by Rampastring** [comment]
Fixed in version 1.87.
