### ISSUE TITLE
Delay on 'New Game' button

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#4]
There is a bit of a delay up to a second, in creating a new game. Is this normal behaviour?

**Comment by Rampastring** [comment]
It is normal behaviour as the client needs to ping all the tunnel servers to figure out the most optimal one for the game.

Of course there could be a progress bar for the operation, but it is usually fairly short and so I'm not really sure if one is necessary.

**Comment by Rampastring** [comment]
If I implement this https://github.com/CnCNet/yr-client/issues/29 it'd pretty much solve this too.
So I'll close this one.
