### ISSUE TITLE
Can't find the source code for YR client.

### ISSUE THREAD

**Issue by FaizanYounasTanooli** [CnCNet/yr-client#41]
Please guide me where is the source code for the YR client.
I want to make windows 8 and above based cool responsive GUI.

**Comment by hifi** [comment]
The client (not game modifications) is https://github.com/CnCNet/xna-cncnet-client

AFAIK the game modifications have not been released publicly.

**Comment by ITsFazi** [comment]
Can you please guide me how can I switch from Dawn of the Tiberium Age to YR
I am mostly familiar with making management applications. Didn’t worked on project like this
I selected YRRlease/Debug but still it loads Dawn of the Tiberium

how can I load the YRclient  ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by hifi** [comment]
You'd probably get better answers on CnCNet Discord as I'm not the developer of the client.
