### ISSUE TITLE
Logging into client takes more than one attempt

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#8]
Can confirm this has happened to myself and others too.  To be investigated?
Reference: http://cnc-comm.com/community/index.php?topic=3592.msg27235#msg27235

**Comment by GrantBartlett** [comment]
![screen shot 2015-04-16 at 19 00 50](https://cloud.githubusercontent.com/assets/6104940/7189383/7e184a2e-e476-11e4-9793-1481ead32a0c.png)

**Comment by Rampastring** [comment]
This is actually a server issue. I'll likely add a workaround for it though.

**Comment by Rampastring** [comment]
Should be fixed in the latest version. The client attempts re-connecting if the session was cut.
